// Code generated by openapigo. DO NOT EDIT.
//
// Source: swagger.json
// Generator version: 0.1.0
package circleciapi

import (
	"encoding/base64"
	"github.com/mkusaka/openapigo"
	"net/http"
)

// WithAPIKeyHeaderAuth returns an Option that sets the "Circle-Token" header parameter.
// Project API tokens are not supported for API v2. Use a personal API token.
func WithAPIKeyHeaderAuth(token string) openapigo.Option {
	return openapigo.WithMiddleware(openapigo.MiddlewareFunc(func(req *http.Request, next func(*http.Request) (*http.Response, error)) (*http.Response, error) {
		req.Header.Set("Circle-Token", token)
		return next(req)
	}))
}

// WithAPIKeyQueryAuth returns an Option that sets the "circle-token" query parameter.
// DEPRECATED - we will remove this option in the future. Project API tokens are not supported for API v2. Use a personal API token.
func WithAPIKeyQueryAuth(token string) openapigo.Option {
	return openapigo.WithMiddleware(openapigo.MiddlewareFunc(func(req *http.Request, next func(*http.Request) (*http.Response, error)) (*http.Response, error) {
		q := req.URL.Query()
		q.Set("circle-token", token)
		req.URL.RawQuery = q.Encode()
		return next(req)
	}))
}

// WithBasicAuth returns an Option that sets HTTP Basic authentication.
// HTTP basic authentication. The username should be set as the circle-token value, and the password should be left blank. Note that project tokens are currently not supported on API v2.
func WithBasicAuth(username, password string) openapigo.Option {
	cred := base64.StdEncoding.EncodeToString([]byte(username + ":" + password))
	return openapigo.WithMiddleware(openapigo.MiddlewareFunc(func(req *http.Request, next func(*http.Request) (*http.Response, error)) (*http.Response, error) {
		req.Header.Set("Authorization", "Basic "+cred)
		return next(req)
	}))
}
