// Code generated by openapigo. DO NOT EDIT.
//
// Source: swagger.json
// Generator version: 0.1.0
package circleciapi

import (
	"github.com/mkusaka/openapigo"
	"net/http"
)

// GetProjectWorkflowsPageData is the endpoint for GET /insights/pages/{provider}/{organization}/{project}/summary.
// Get summary metrics and trends for a project across it's workflows and branches
var GetProjectWorkflowsPageData = openapigo.NewEndpoint[GetProjectWorkflowsPageDataParams, GetProjectWorkflowsPageDataResponse]("GET", "/insights/pages/{provider}/{organization}/{project}/summary").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetJobTimeseries is the endpoint for GET /insights/time-series/{provider}/{organization}/{project}/workflows/{workflow-name}/jobs.
// Job timeseries data
var GetJobTimeseries = openapigo.NewEndpoint[GetJobTimeseriesParams, GetJobTimeseriesResponse]("GET", "/insights/time-series/{provider}/{organization}/{project}/workflows/{workflow-name}/jobs").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetOrgSummaryData is the endpoint for GET /insights/{provider}/{organization}/summary.
// Get summary metrics with trends for the entire org, and for each project.
var GetOrgSummaryData = openapigo.NewEndpoint[GetOrgSummaryDataParams, GetOrgSummaryDataResponse]("GET", "/insights/{provider}/{organization}/summary").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetAllInsightsBranches is the endpoint for GET /insights/{provider}/{organization}/{project}/branches.
// Get all branches for a project
var GetAllInsightsBranches = openapigo.NewEndpoint[GetAllInsightsBranchesParams, GetAllInsightsBranchesResponse]("GET", "/insights/{provider}/{organization}/{project}/branches").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetFlakyTests is the endpoint for GET /insights/{provider}/{organization}/{project}/flaky-tests.
// Get flaky tests for a project
var GetFlakyTests = openapigo.NewEndpoint[GetFlakyTestsParams, GetFlakyTestsResponse]("GET", "/insights/{provider}/{organization}/{project}/flaky-tests").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetProjectWorkflowMetrics is the endpoint for GET /insights/{provider}/{organization}/{project}/workflows.
// Get summary metrics for a project's workflows
var GetProjectWorkflowMetrics = openapigo.NewEndpoint[GetProjectWorkflowMetricsParams, GetProjectWorkflowMetricsResponse]("GET", "/insights/{provider}/{organization}/{project}/workflows").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetProjectWorkflowRuns is the endpoint for GET /insights/{provider}/{organization}/{project}/workflows/{workflow-name}.
// Get recent runs of a workflow
var GetProjectWorkflowRuns = openapigo.NewEndpoint[GetProjectWorkflowRunsParams, GetProjectWorkflowRunsResponse]("GET", "/insights/{provider}/{organization}/{project}/workflows/{workflow-name}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetProjectWorkflowJobMetrics is the endpoint for GET /insights/{provider}/{organization}/{project}/workflows/{workflow-name}/jobs.
// Get summary metrics for a project workflow's jobs.
var GetProjectWorkflowJobMetrics = openapigo.NewEndpoint[GetProjectWorkflowJobMetricsParams, GetProjectWorkflowJobMetricsResponse]("GET", "/insights/{provider}/{organization}/{project}/workflows/{workflow-name}/jobs").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetWorkflowSummary is the endpoint for GET /insights/{provider}/{organization}/{project}/workflows/{workflow-name}/summary.
// Get metrics and trends for workflows
var GetWorkflowSummary = openapigo.NewEndpoint[GetWorkflowSummaryParams, GetWorkflowSummaryResponse]("GET", "/insights/{provider}/{organization}/{project}/workflows/{workflow-name}/summary").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetProjectWorkflowTestMetrics is the endpoint for GET /insights/{provider}/{organization}/{project}/workflows/{workflow-name}/test-metrics.
// Get test metrics for a project's workflows
var GetProjectWorkflowTestMetrics = openapigo.NewEndpoint[GetProjectWorkflowTestMetricsParams, GetProjectWorkflowTestMetricsResponse]("GET", "/insights/{provider}/{organization}/{project}/workflows/{workflow-name}/test-metrics").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CancelJobByJobID is the endpoint for POST /jobs/{job-id}/cancel.
// Cancel job by job ID
var CancelJobByJobID = openapigo.NewEndpoint[CancelJobByJobIDParams, CancelJobByJobIDResponse]("POST", "/jobs/{job-id}/cancel").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetCurrentUser is the endpoint for GET /me.
// User Information
var GetCurrentUser = openapigo.NewEndpoint[openapigo.NoRequest, GetCurrentUserResponse]("GET", "/me").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetCollaborations is the endpoint for GET /me/collaborations.
// Collaborations
var GetCollaborations = openapigo.NewEndpoint[openapigo.NoRequest, []GetCollaborationsResponseItem]("GET", "/me/collaborations").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreateOrganization is the endpoint for POST /organization.
// Create a new organization
var CreateOrganization = openapigo.NewEndpoint[CreateOrganizationParams, CreateOrganizationResponse]("POST", "/organization").
	WithSuccessCodes(201).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetOrganization is the endpoint for GET /organization/{org-slug-or-id}.
// Get an organization
var GetOrganization = openapigo.NewEndpoint[GetOrganizationParams, GetOrganizationResponse]("GET", "/organization/{org-slug-or-id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// DeleteOrganization is the endpoint for DELETE /organization/{org-slug-or-id}.
// Delete an organization
var DeleteOrganization = openapigo.NewEndpoint[DeleteOrganizationParams, DeleteOrganizationResponse]("DELETE", "/organization/{org-slug-or-id}").
	WithSuccessCodes(202).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreateProject is the endpoint for POST /organization/{org-slug-or-id}/project.
// Create a new project
var CreateProject = openapigo.NewEndpoint[CreateProjectParams, CreateProjectResponse]("POST", "/organization/{org-slug-or-id}/project").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListURLOrbAllowListEntries is the endpoint for GET /organization/{org-slug-or-id}/url-orb-allow-list.
// List the entries in the org's URL Orb allow-list
var ListURLOrbAllowListEntries = openapigo.NewEndpoint[ListURLOrbAllowListEntriesParams, ListURLOrbAllowListEntriesResponse]("GET", "/organization/{org-slug-or-id}/url-orb-allow-list").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreateURLOrbAllowListEntry is the endpoint for POST /organization/{org-slug-or-id}/url-orb-allow-list.
// Create a new URL Orb allow-list entry
var CreateURLOrbAllowListEntry = openapigo.NewEndpoint[CreateURLOrbAllowListEntryParams, CreateURLOrbAllowListEntryResponse]("POST", "/organization/{org-slug-or-id}/url-orb-allow-list").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// RemoveURLOrbAllowListEntry is the endpoint for DELETE /organization/{org-slug-or-id}/url-orb-allow-list/{allow-list-entry-id}.
// Remove an entry from the org's URL orb allow-list
var RemoveURLOrbAllowListEntry = openapigo.NewEndpoint[RemoveURLOrbAllowListEntryParams, RemoveURLOrbAllowListEntryResponse]("DELETE", "/organization/{org-slug-or-id}/url-orb-allow-list/{allow-list-entry-id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListPipelines is the endpoint for GET /pipeline.
// Get a list of pipelines
var ListPipelines = openapigo.NewEndpoint[ListPipelinesParams, ListPipelinesResponse]("GET", "/pipeline").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ContinuePipeline is the endpoint for POST /pipeline/continue.
// Continue a pipeline
var ContinuePipeline = openapigo.NewEndpoint[ContinuePipelineParams, ContinuePipelineResponse]("POST", "/pipeline/continue").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetPipelineByID is the endpoint for GET /pipeline/{pipeline-id}.
// Get a pipeline by ID
var GetPipelineByID = openapigo.NewEndpoint[GetPipelineByIDParams, GetPipelineByIDResponse]("GET", "/pipeline/{pipeline-id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetPipelineConfigByID is the endpoint for GET /pipeline/{pipeline-id}/config.
// Get a pipeline's configuration
var GetPipelineConfigByID = openapigo.NewEndpoint[GetPipelineConfigByIDParams, GetPipelineConfigByIDResponse]("GET", "/pipeline/{pipeline-id}/config").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetPipelineValuesByID is the endpoint for GET /pipeline/{pipeline-id}/values.
// Get pipeline values for a pipeline
var GetPipelineValuesByID = openapigo.NewEndpoint[GetPipelineValuesByIDParams, map[string]any]("GET", "/pipeline/{pipeline-id}/values").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListWorkflowsByPipelineID is the endpoint for GET /pipeline/{pipeline-id}/workflow.
// Get a pipeline's workflows
var ListWorkflowsByPipelineID = openapigo.NewEndpoint[ListWorkflowsByPipelineIDParams, ListWorkflowsByPipelineIDResponse]("GET", "/pipeline/{pipeline-id}/workflow").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetProjectBySlug is the endpoint for GET /project/{provider}/{organization}/{project}.
// Get a project
var GetProjectBySlug = openapigo.NewEndpoint[GetProjectBySlugParams, GetProjectBySlugResponse]("GET", "/project/{provider}/{organization}/{project}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreateProject1 is the endpoint for POST /project/{provider}/{organization}/{project}.
// ⚠️ Create a project
var CreateProject1 = openapigo.NewEndpoint[CreateProject1Params, ProjectSettings]("POST", "/project/{provider}/{organization}/{project}").
	WithSuccessCodes(201).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 405, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// DeleteProjectBySlug is the endpoint for DELETE /project/{provider}/{organization}/{project}.
// Delete a project
var DeleteProjectBySlug = openapigo.NewEndpoint[DeleteProjectBySlugParams, DeleteProjectBySlugResponse]("DELETE", "/project/{provider}/{organization}/{project}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListCheckoutKeys is the endpoint for GET /project/{provider}/{organization}/{project}/checkout-key.
// Get all checkout keys
var ListCheckoutKeys = openapigo.NewEndpoint[ListCheckoutKeysParams, ListCheckoutKeysResponse]("GET", "/project/{provider}/{organization}/{project}/checkout-key").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreateCheckoutKey is the endpoint for POST /project/{provider}/{organization}/{project}/checkout-key.
// Create a new checkout key
var CreateCheckoutKey = openapigo.NewEndpoint[CreateCheckoutKeyParams, CreateCheckoutKeyResponse]("POST", "/project/{provider}/{organization}/{project}/checkout-key").
	WithSuccessCodes(201).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetCheckoutKey is the endpoint for GET /project/{provider}/{organization}/{project}/checkout-key/{fingerprint}.
// Get a checkout key
var GetCheckoutKey = openapigo.NewEndpoint[GetCheckoutKeyParams, GetCheckoutKeyResponse]("GET", "/project/{provider}/{organization}/{project}/checkout-key/{fingerprint}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// DeleteCheckoutKey is the endpoint for DELETE /project/{provider}/{organization}/{project}/checkout-key/{fingerprint}.
// Delete a checkout key
var DeleteCheckoutKey = openapigo.NewEndpoint[DeleteCheckoutKeyParams, DeleteCheckoutKeyResponse]("DELETE", "/project/{provider}/{organization}/{project}/checkout-key/{fingerprint}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListEnvVars is the endpoint for GET /project/{provider}/{organization}/{project}/envvar.
// List all environment variables
var ListEnvVars = openapigo.NewEndpoint[ListEnvVarsParams, ListEnvVarsResponse]("GET", "/project/{provider}/{organization}/{project}/envvar").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreateEnvVar is the endpoint for POST /project/{provider}/{organization}/{project}/envvar.
// Create an environment variable
var CreateEnvVar = openapigo.NewEndpoint[CreateEnvVarParams, CreateEnvVarResponse]("POST", "/project/{provider}/{organization}/{project}/envvar").
	WithSuccessCodes(201).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetEnvVar is the endpoint for GET /project/{provider}/{organization}/{project}/envvar/{name}.
// Get a masked environment variable
var GetEnvVar = openapigo.NewEndpoint[GetEnvVarParams, GetEnvVarResponse]("GET", "/project/{provider}/{organization}/{project}/envvar/{name}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// DeleteEnvVarOp is the endpoint for DELETE /project/{provider}/{organization}/{project}/envvar/{name}.
// Delete an environment variable
var DeleteEnvVarOp = openapigo.NewEndpoint[DeleteEnvVarOpParams, DeleteEnvVarOpResponse]("DELETE", "/project/{provider}/{organization}/{project}/envvar/{name}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetJobDetails is the endpoint for GET /project/{provider}/{organization}/{project}/job/{job-number}.
// Get job details
var GetJobDetails = openapigo.NewEndpoint[GetJobDetailsParams, GetJobDetailsResponse]("GET", "/project/{provider}/{organization}/{project}/job/{job-number}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CancelJobByJobNumber is the endpoint for POST /project/{provider}/{organization}/{project}/job/{job-number}/cancel.
// Cancel job by job number
var CancelJobByJobNumber = openapigo.NewEndpoint[CancelJobByJobNumberParams, CancelJobByJobNumberResponse]("POST", "/project/{provider}/{organization}/{project}/job/{job-number}/cancel").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListPipelinesForProject is the endpoint for GET /project/{provider}/{organization}/{project}/pipeline.
// Get all pipelines
var ListPipelinesForProject = openapigo.NewEndpoint[ListPipelinesForProjectParams, ListPipelinesForProjectResponse]("GET", "/project/{provider}/{organization}/{project}/pipeline").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// TriggerPipeline is the endpoint for POST /project/{provider}/{organization}/{project}/pipeline.
// Trigger a new pipeline
var TriggerPipeline = openapigo.NewEndpoint[TriggerPipelineParams, TriggerPipelineResponse]("POST", "/project/{provider}/{organization}/{project}/pipeline").
	WithSuccessCodes(201).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListMyPipelines is the endpoint for GET /project/{provider}/{organization}/{project}/pipeline/mine.
// Get your pipelines
var ListMyPipelines = openapigo.NewEndpoint[ListMyPipelinesParams, ListMyPipelinesResponse]("GET", "/project/{provider}/{organization}/{project}/pipeline/mine").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetPipelineByNumber is the endpoint for GET /project/{provider}/{organization}/{project}/pipeline/{pipeline-number}.
// Get a pipeline by pipeline number
var GetPipelineByNumber = openapigo.NewEndpoint[GetPipelineByNumberParams, GetPipelineByNumberResponse]("GET", "/project/{provider}/{organization}/{project}/pipeline/{pipeline-number}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListSchedulesForProject is the endpoint for GET /project/{provider}/{organization}/{project}/schedule.
// List schedule triggers
var ListSchedulesForProject = openapigo.NewEndpoint[ListSchedulesForProjectParams, ListSchedulesForProjectResponse]("GET", "/project/{provider}/{organization}/{project}/schedule").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreateSchedule is the endpoint for POST /project/{provider}/{organization}/{project}/schedule.
// Create a schedule
var CreateSchedule = openapigo.NewEndpoint[CreateScheduleParams, CreateScheduleResponse]("POST", "/project/{provider}/{organization}/{project}/schedule").
	WithSuccessCodes(201).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetJobArtifacts is the endpoint for GET /project/{provider}/{organization}/{project}/{job-number}/artifacts.
// Get a job's artifacts
var GetJobArtifacts = openapigo.NewEndpoint[GetJobArtifactsParams, GetJobArtifactsResponse]("GET", "/project/{provider}/{organization}/{project}/{job-number}/artifacts").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetTests is the endpoint for GET /project/{provider}/{organization}/{project}/{job-number}/tests.
// Get test metadata
var GetTests = openapigo.NewEndpoint[GetTestsParams, GetTestsResponse]("GET", "/project/{provider}/{organization}/{project}/{job-number}/tests").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetScheduleByID is the endpoint for GET /schedule/{schedule-id}.
// Get a schedule by ID. Available only on schedules associated with GitHub OAuth or Bitbucket Cloud pipeline definitions.
var GetScheduleByID = openapigo.NewEndpoint[GetScheduleByIDParams, GetScheduleByIDResponse]("GET", "/schedule/{schedule-id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// UpdateSchedule is the endpoint for PATCH /schedule/{schedule-id}.
// Update a schedule
var UpdateSchedule = openapigo.NewEndpoint[UpdateScheduleParams, UpdateScheduleResponse]("PATCH", "/schedule/{schedule-id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// DeleteScheduleByID is the endpoint for DELETE /schedule/{schedule-id}.
// Delete a schedule
var DeleteScheduleByID = openapigo.NewEndpoint[DeleteScheduleByIDParams, DeleteScheduleByIDResponse]("DELETE", "/schedule/{schedule-id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetUser is the endpoint for GET /user/{id}.
// User Information
var GetUser = openapigo.NewEndpoint[GetUserParams, GetUserResponse]("GET", "/user/{id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetWebhooks is the endpoint for GET /webhook.
// List webhooks
var GetWebhooks = openapigo.NewEndpoint[GetWebhooksParams, GetWebhooksResponse]("GET", "/webhook").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreateWebhook is the endpoint for POST /webhook.
// Create an outbound webhook
var CreateWebhook = openapigo.NewEndpoint[CreateWebhookParams, CreateWebhookResponse]("POST", "/webhook").
	WithSuccessCodes(201).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetWebhookByID is the endpoint for GET /webhook/{webhook-id}.
// Get a webhook
var GetWebhookByID = openapigo.NewEndpoint[GetWebhookByIDParams, GetWebhookByIDResponse]("GET", "/webhook/{webhook-id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// UpdateWebhook is the endpoint for PUT /webhook/{webhook-id}.
// Update an outbound webhook
var UpdateWebhook = openapigo.NewEndpoint[UpdateWebhookParams, UpdateWebhookResponse]("PUT", "/webhook/{webhook-id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// DeleteWebhook is the endpoint for DELETE /webhook/{webhook-id}.
// Delete an outbound webhook
var DeleteWebhook = openapigo.NewEndpoint[DeleteWebhookParams, DeleteWebhookResponse]("DELETE", "/webhook/{webhook-id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetWorkflowByID is the endpoint for GET /workflow/{id}.
// Get a workflow
var GetWorkflowByID = openapigo.NewEndpoint[GetWorkflowByIDParams, GetWorkflowByIDResponse]("GET", "/workflow/{id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ApprovePendingApprovalJobByID is the endpoint for POST /workflow/{id}/approve/{approval_request_id}.
// Approve a job
var ApprovePendingApprovalJobByID = openapigo.NewEndpoint[ApprovePendingApprovalJobByIDParams, ApprovePendingApprovalJobByIDResponse]("POST", "/workflow/{id}/approve/{approval_request_id}").
	WithSuccessCodes(202).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CancelWorkflow is the endpoint for POST /workflow/{id}/cancel.
// Cancel a workflow
var CancelWorkflow = openapigo.NewEndpoint[CancelWorkflowParams, CancelWorkflowResponse]("POST", "/workflow/{id}/cancel").
	WithSuccessCodes(202).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListWorkflowJobs is the endpoint for GET /workflow/{id}/job.
// Get a workflow's jobs
var ListWorkflowJobs = openapigo.NewEndpoint[ListWorkflowJobsParams, ListWorkflowJobsResponse]("GET", "/workflow/{id}/job").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// RerunWorkflow is the endpoint for POST /workflow/{id}/rerun.
// Rerun a workflow
var RerunWorkflow = openapigo.NewEndpoint[RerunWorkflowParams, RerunWorkflowResponse]("POST", "/workflow/{id}/rerun").
	WithSuccessCodes(202).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 0, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetOrgClaims is the endpoint for GET /org/{orgID}/oidc-custom-claims.
// Get org-level claims
var GetOrgClaims = openapigo.NewEndpoint[GetOrgClaimsParams, ClaimResponse]("GET", "/org/{orgID}/oidc-custom-claims").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// PatchOrgClaims is the endpoint for PATCH /org/{orgID}/oidc-custom-claims.
// Patch org-level claims
var PatchOrgClaims = openapigo.NewEndpoint[PatchOrgClaimsParams, ClaimResponse]("PATCH", "/org/{orgID}/oidc-custom-claims").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// DeleteOrgClaims is the endpoint for DELETE /org/{orgID}/oidc-custom-claims.
// Delete org-level claims
var DeleteOrgClaims = openapigo.NewEndpoint[DeleteOrgClaimsParams, ClaimResponse]("DELETE", "/org/{orgID}/oidc-custom-claims").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetProjectClaims is the endpoint for GET /org/{orgID}/project/{projectID}/oidc-custom-claims.
// Get project-level claims
var GetProjectClaims = openapigo.NewEndpoint[GetProjectClaimsParams, ClaimResponse]("GET", "/org/{orgID}/project/{projectID}/oidc-custom-claims").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// PatchProjectClaims is the endpoint for PATCH /org/{orgID}/project/{projectID}/oidc-custom-claims.
// Patch project-level claims
var PatchProjectClaims = openapigo.NewEndpoint[PatchProjectClaimsParams, ClaimResponse]("PATCH", "/org/{orgID}/project/{projectID}/oidc-custom-claims").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// DeleteProjectClaims is the endpoint for DELETE /org/{orgID}/project/{projectID}/oidc-custom-claims.
// Delete project-level claims
var DeleteProjectClaims = openapigo.NewEndpoint[DeleteProjectClaimsParams, ClaimResponse]("DELETE", "/org/{orgID}/project/{projectID}/oidc-custom-claims").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetDecisionLogs is the endpoint for GET /owner/{ownerID}/context/{context}/decision.
// Retrieves the owner's decision audit logs.
var GetDecisionLogs = openapigo.NewEndpoint[GetDecisionLogsParams, []DecisionLog]("GET", "/owner/{ownerID}/context/{context}/decision").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// MakeDecision is the endpoint for POST /owner/{ownerID}/context/{context}/decision.
// Makes a decision
var MakeDecision = openapigo.NewEndpoint[MakeDecisionParams, Decision]("POST", "/owner/{ownerID}/context/{context}/decision").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetDecisionSettings is the endpoint for GET /owner/{ownerID}/context/{context}/decision/settings.
// Get the decision settings
var GetDecisionSettings = openapigo.NewEndpoint[GetDecisionSettingsParams, DecisionSettings]("GET", "/owner/{ownerID}/context/{context}/decision/settings").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// SetDecisionSettings is the endpoint for PATCH /owner/{ownerID}/context/{context}/decision/settings.
// Set the decision settings
var SetDecisionSettings = openapigo.NewEndpoint[SetDecisionSettingsParams, DecisionSettings]("PATCH", "/owner/{ownerID}/context/{context}/decision/settings").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetDecisionLog is the endpoint for GET /owner/{ownerID}/context/{context}/decision/{decisionID}.
// Retrieves the owner's decision audit log by given decisionID
var GetDecisionLog = openapigo.NewEndpoint[GetDecisionLogParams, DecisionLog]("GET", "/owner/{ownerID}/context/{context}/decision/{decisionID}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetDecisionLogPolicyBundle is the endpoint for GET /owner/{ownerID}/context/{context}/decision/{decisionID}/policy-bundle.
// Retrieves Policy Bundle for a given decision log ID
var GetDecisionLogPolicyBundle = openapigo.NewEndpoint[GetDecisionLogPolicyBundleParams, PolicyBundle]("GET", "/owner/{ownerID}/context/{context}/decision/{decisionID}/policy-bundle").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetPolicyBundle is the endpoint for GET /owner/{ownerID}/context/{context}/policy-bundle.
// Retrieves Policy Bundle
var GetPolicyBundle = openapigo.NewEndpoint[GetPolicyBundleParams, PolicyBundle]("GET", "/owner/{ownerID}/context/{context}/policy-bundle").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreatePolicyBundle is the endpoint for POST /owner/{ownerID}/context/{context}/policy-bundle.
// Creates policy bundle for the context
var CreatePolicyBundle = openapigo.NewEndpoint[CreatePolicyBundleParams, BundleDiff]("POST", "/owner/{ownerID}/context/{context}/policy-bundle").
	WithSuccessCodes(200, 201).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 413, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetPolicyDocument is the endpoint for GET /owner/{ownerID}/context/{context}/policy-bundle/{policyName}.
// Retrieves a policy document
var GetPolicyDocument = openapigo.NewEndpoint[GetPolicyDocumentParams, Policy]("GET", "/owner/{ownerID}/context/{context}/policy-bundle/{policyName}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListContexts is the endpoint for GET /context.
// List contexts
var ListContexts = openapigo.NewEndpoint[ListContextsParams, ContextList]("GET", "/context").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreateContext is the endpoint for POST /context.
// Create a new context
var CreateContext = openapigo.NewEndpoint[CreateContextParams, CreateContextResponse]("POST", "/context").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetContext is the endpoint for GET /context/{context_id}.
// Get a context
var GetContext = openapigo.NewEndpoint[GetContextParams, Context]("GET", "/context/{context_id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// DeleteContext is the endpoint for DELETE /context/{context_id}.
// Delete a context
var DeleteContext = openapigo.NewEndpoint[DeleteContextParams, DeleteContextResponse]("DELETE", "/context/{context_id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListEnvironmentVariablesFromContext is the endpoint for GET /context/{context_id}/environment-variable.
// List environment variables
var ListEnvironmentVariablesFromContext = openapigo.NewEndpoint[ListEnvironmentVariablesFromContextParams, EnvVarList]("GET", "/context/{context_id}/environment-variable").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// AddEnvironmentVariableToContext is the endpoint for PUT /context/{context_id}/environment-variable/{env_var_name}.
// Add or update an environment variable
var AddEnvironmentVariableToContext = openapigo.NewEndpoint[AddEnvironmentVariableToContextParams, UpdateEnvVar]("PUT", "/context/{context_id}/environment-variable/{env_var_name}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// DeleteEnvironmentVariableFromContext is the endpoint for DELETE /context/{context_id}/environment-variable/{env_var_name}.
// Remove an environment variable
var DeleteEnvironmentVariableFromContext = openapigo.NewEndpoint[DeleteEnvironmentVariableFromContextParams, DeleteEnvVar]("DELETE", "/context/{context_id}/environment-variable/{env_var_name}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetContextRestrictions is the endpoint for GET /context/{context_id}/restrictions.
// Get context restrictions
var GetContextRestrictions = openapigo.NewEndpoint[GetContextRestrictionsParams, ContextProjectRestrictionsList]("GET", "/context/{context_id}/restrictions").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreateContextRestriction is the endpoint for POST /context/{context_id}/restrictions.
// Create context restriction
var CreateContextRestriction = openapigo.NewEndpoint[CreateContextRestrictionParams, RestrictionCreated]("POST", "/context/{context_id}/restrictions").
	WithSuccessCodes(201).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 409, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// DeleteContextRestriction is the endpoint for DELETE /context/{context_id}/restrictions/{restriction_id}.
// Delete context restriction
var DeleteContextRestriction = openapigo.NewEndpoint[DeleteContextRestrictionParams, RestrictionDeleted]("DELETE", "/context/{context_id}/restrictions/{restriction_id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetProjectSettings is the endpoint for GET /project/{provider}/{organization}/{project}/settings.
// Get project settings
var GetProjectSettings = openapigo.NewEndpoint[GetProjectSettingsParams, ProjectSettings]("GET", "/project/{provider}/{organization}/{project}/settings").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// PatchProjectSettings is the endpoint for PATCH /project/{provider}/{organization}/{project}/settings.
// Update project settings
var PatchProjectSettings = openapigo.NewEndpoint[PatchProjectSettingsParams, ProjectSettings]("PATCH", "/project/{provider}/{organization}/{project}/settings").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetOrganizationGroups is the endpoint for GET /organizations/{org_id}/groups.
// Groups in an organization
var GetOrganizationGroups = openapigo.NewEndpoint[GetOrganizationGroupsParams, Groups]("GET", "/organizations/{org_id}/groups").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreateOrganizationGroup is the endpoint for POST /organizations/{org_id}/groups.
// Create Groups
var CreateOrganizationGroup = openapigo.NewEndpoint[CreateOrganizationGroupParams, Group]("POST", "/organizations/{org_id}/groups").
	WithSuccessCodes(201).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 409, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetGroup is the endpoint for GET /organizations/{org_id}/groups/{group_id}.
// A group in an organization
var GetGroup = openapigo.NewEndpoint[GetGroupParams, Group]("GET", "/organizations/{org_id}/groups/{group_id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// DeleteGroup is the endpoint for DELETE /organizations/{org_id}/groups/{group_id}.
// Delete a group
var DeleteGroup = openapigo.NewEndpoint[DeleteGroupParams, DeleteGroupResponse]("DELETE", "/organizations/{org_id}/groups/{group_id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 403, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreateUsageExport is the endpoint for POST /organizations/{org_id}/usage_export_job.
// Create a usage export
var CreateUsageExport = openapigo.NewEndpoint[CreateUsageExportParams, UsageExportJob]("POST", "/organizations/{org_id}/usage_export_job").
	WithSuccessCodes(201).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetUsageExport is the endpoint for GET /organizations/{org_id}/usage_export_job/{usage_export_job_id}.
// Get a usage export
var GetUsageExport = openapigo.NewEndpoint[GetUsageExportParams, GetUsageExportJobStatus]("GET", "/organizations/{org_id}/usage_export_job/{usage_export_job_id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 429, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// TriggerPipelineRun is the endpoint for POST /project/{provider}/{organization}/{project}/pipeline/run.
// [Recommended] Trigger a new pipeline
var TriggerPipelineRun = openapigo.NewEndpoint[TriggerPipelineRunParams, PipelineNotTriggeredResponse]("POST", "/project/{provider}/{organization}/{project}/pipeline/run").
	WithSuccessCodes(200, 201).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListPipelineDefinitions is the endpoint for GET /projects/{project_id}/pipeline-definitions.
// List pipeline definitions
var ListPipelineDefinitions = openapigo.NewEndpoint[ListPipelineDefinitionsParams, PipelineDefinitionList]("GET", "/projects/{project_id}/pipeline-definitions").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreatePipelineDefinition is the endpoint for POST /projects/{project_id}/pipeline-definitions.
// Create pipeline definition
var CreatePipelineDefinition = openapigo.NewEndpoint[CreatePipelineDefinitionParams, PipelineDefinition]("POST", "/projects/{project_id}/pipeline-definitions").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetPipelineDefinition is the endpoint for GET /projects/{project_id}/pipeline-definitions/{pipeline_definition_id}.
// Get pipeline definition
var GetPipelineDefinition = openapigo.NewEndpoint[GetPipelineDefinitionParams, PipelineDefinition]("GET", "/projects/{project_id}/pipeline-definitions/{pipeline_definition_id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// UpdatePipelineDefinition is the endpoint for PATCH /projects/{project_id}/pipeline-definitions/{pipeline_definition_id}.
// Update pipeline definition
var UpdatePipelineDefinition = openapigo.NewEndpoint[UpdatePipelineDefinitionParams, PipelineDefinition]("PATCH", "/projects/{project_id}/pipeline-definitions/{pipeline_definition_id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// DeletePipelineDefinition is the endpoint for DELETE /projects/{project_id}/pipeline-definitions/{pipeline_definition_id}.
// Delete pipeline definition
var DeletePipelineDefinition = openapigo.NewEndpoint[DeletePipelineDefinitionParams, PipelineDefinitionDeleted]("DELETE", "/projects/{project_id}/pipeline-definitions/{pipeline_definition_id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListPipelineDefinitionTriggers is the endpoint for GET /projects/{project_id}/pipeline-definitions/{pipeline_definition_id}/triggers.
// List pipeline definition triggers
var ListPipelineDefinitionTriggers = openapigo.NewEndpoint[ListPipelineDefinitionTriggersParams, TriggerList]("GET", "/projects/{project_id}/pipeline-definitions/{pipeline_definition_id}/triggers").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// CreateTrigger is the endpoint for POST /projects/{project_id}/pipeline-definitions/{pipeline_definition_id}/triggers.
// Create trigger
var CreateTrigger = openapigo.NewEndpoint[CreateTriggerParams, Trigger]("POST", "/projects/{project_id}/pipeline-definitions/{pipeline_definition_id}/triggers").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetTrigger is the endpoint for GET /projects/{project_id}/triggers/{trigger_id}.
// Get trigger
var GetTrigger = openapigo.NewEndpoint[GetTriggerParams, Trigger]("GET", "/projects/{project_id}/triggers/{trigger_id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// UpdateTrigger is the endpoint for PATCH /projects/{project_id}/triggers/{trigger_id}.
// Update trigger
var UpdateTrigger = openapigo.NewEndpoint[UpdateTriggerParams, Trigger]("PATCH", "/projects/{project_id}/triggers/{trigger_id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// DeleteTrigger is the endpoint for DELETE /projects/{project_id}/triggers/{trigger_id}.
// Delete trigger
var DeleteTrigger = openapigo.NewEndpoint[DeleteTriggerParams, TriggerDeleted]("DELETE", "/projects/{project_id}/triggers/{trigger_id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 401, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// RollbackProject is the endpoint for POST /projects/{project_id}/rollback.
// Rollback a project
var RollbackProject = openapigo.NewEndpoint[RollbackProjectParams, RollbackProjectResponse]("POST", "/projects/{project_id}/rollback").
	WithSuccessCodes(202).
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 409, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListEnvironments is the endpoint for GET /deploy/environments.
// List Environments
var ListEnvironments = openapigo.NewEndpoint[ListEnvironmentsParams, PaginatedEnvironmentList]("GET", "/deploy/environments").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetEnvironment is the endpoint for GET /deploy/environments/{environment_id}.
// Get Environment
var GetEnvironment = openapigo.NewEndpoint[GetEnvironmentParams, Environment]("GET", "/deploy/environments/{environment_id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListComponents is the endpoint for GET /deploy/components.
// List Components
var ListComponents = openapigo.NewEndpoint[ListComponentsParams, PaginatedComponentList]("GET", "/deploy/components").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// GetComponent is the endpoint for GET /deploy/components/{component_id}.
// Get Component
var GetComponent = openapigo.NewEndpoint[GetComponentParams, Component]("GET", "/deploy/components/{component_id}").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)

// ListComponentVersions is the endpoint for GET /deploy/components/{component_id}/versions.
// List Component Versions
var ListComponentVersions = openapigo.NewEndpoint[ListComponentVersionsParams, PaginatedComponentVersionList]("GET", "/deploy/components/{component_id}/versions").
	WithErrors(
		openapigo.ErrorHandler{StatusCode: 400, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 404, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
		openapigo.ErrorHandler{StatusCode: 500, Parse: func(code int, header http.Header, body []byte) error {
			return &openapigo.APIError{StatusCode: code, Status: http.StatusText(code), Header: header, Body: body}
		}},
	)
