// Code generated by openapigo. DO NOT EDIT.
//
// Source: swagger.json
// Generator version: 0.1.0
package circleciapi

import (
	"time"
)

// GetProjectWorkflowsPageDataParams is the request parameters for getProjectWorkflowsPageData.
type GetProjectWorkflowsPageDataParams struct {
	Provider        string          `path:"provider"`
	Organization    string          `path:"organization"`
	Project         string          `path:"project"`
	ReportingWindow *string         `query:"reporting-window"`
	Branches        *map[string]any `query:"branches"`
	WorkflowNames   *map[string]any `query:"workflow-names"`
}

// GetJobTimeseriesParams is the request parameters for getJobTimeseries.
type GetJobTimeseriesParams struct {
	Provider     string     `path:"provider"`
	Organization string     `path:"organization"`
	Project      string     `path:"project"`
	WorkflowName string     `path:"workflow-name"`
	Branch       *string    `query:"branch"`
	Granularity  *string    `query:"granularity"`
	StartDate    *time.Time `query:"start-date"`
	EndDate      *time.Time `query:"end-date"`
}

// GetOrgSummaryDataParams is the request parameters for getOrgSummaryData.
type GetOrgSummaryDataParams struct {
	Provider        string          `path:"provider"`
	Organization    string          `path:"organization"`
	ReportingWindow *string         `query:"reporting-window"`
	ProjectNames    *map[string]any `query:"project-names"`
}

// GetAllInsightsBranchesParams is the request parameters for getAllInsightsBranches.
type GetAllInsightsBranchesParams struct {
	Provider     string  `path:"provider"`
	Organization string  `path:"organization"`
	Project      string  `path:"project"`
	WorkflowName *string `query:"workflow-name"`
}

// GetFlakyTestsParams is the request parameters for getFlakyTests.
type GetFlakyTestsParams struct {
	Provider     string `path:"provider"`
	Organization string `path:"organization"`
	Project      string `path:"project"`
}

// GetProjectWorkflowMetricsParams is the request parameters for getProjectWorkflowMetrics.
type GetProjectWorkflowMetricsParams struct {
	Provider        string  `path:"provider"`
	Organization    string  `path:"organization"`
	Project         string  `path:"project"`
	PageToken       *string `query:"page-token"`
	AllBranches     *bool   `query:"all-branches"`
	Branch          *string `query:"branch"`
	ReportingWindow *string `query:"reporting-window"`
}

// GetProjectWorkflowRunsParams is the request parameters for getProjectWorkflowRuns.
type GetProjectWorkflowRunsParams struct {
	Provider     string     `path:"provider"`
	Organization string     `path:"organization"`
	Project      string     `path:"project"`
	WorkflowName string     `path:"workflow-name"`
	AllBranches  *bool      `query:"all-branches"`
	Branch       *string    `query:"branch"`
	PageToken    *string    `query:"page-token"`
	StartDate    *time.Time `query:"start-date"`
	EndDate      *time.Time `query:"end-date"`
}

// GetProjectWorkflowJobMetricsParams is the request parameters for getProjectWorkflowJobMetrics.
type GetProjectWorkflowJobMetricsParams struct {
	Provider        string  `path:"provider"`
	Organization    string  `path:"organization"`
	Project         string  `path:"project"`
	WorkflowName    string  `path:"workflow-name"`
	PageToken       *string `query:"page-token"`
	AllBranches     *bool   `query:"all-branches"`
	Branch          *string `query:"branch"`
	ReportingWindow *string `query:"reporting-window"`
	JobName         *string `query:"job-name"`
}

// GetWorkflowSummaryParams is the request parameters for getWorkflowSummary.
type GetWorkflowSummaryParams struct {
	Provider     string  `path:"provider"`
	Organization string  `path:"organization"`
	Project      string  `path:"project"`
	WorkflowName string  `path:"workflow-name"`
	AllBranches  *bool   `query:"all-branches"`
	Branch       *string `query:"branch"`
}

// GetProjectWorkflowTestMetricsParams is the request parameters for getProjectWorkflowTestMetrics.
type GetProjectWorkflowTestMetricsParams struct {
	Provider     string  `path:"provider"`
	Organization string  `path:"organization"`
	Project      string  `path:"project"`
	WorkflowName string  `path:"workflow-name"`
	Branch       *string `query:"branch"`
	AllBranches  *bool   `query:"all-branches"`
}

// CancelJobByJobIDParams is the request parameters for cancelJobByJobID.
type CancelJobByJobIDParams struct {
	JobID string `path:"job-id"`
}

// CreateOrganizationParams is the request parameters for createOrganization.
type CreateOrganizationParams struct {
	Body *CreateOrganizationBody `body:"application/json"`
}

// GetOrganizationParams is the request parameters for getOrganization.
type GetOrganizationParams struct {
	OrgSlugOrID string `path:"org-slug-or-id"`
}

// DeleteOrganizationParams is the request parameters for deleteOrganization.
type DeleteOrganizationParams struct {
	OrgSlugOrID string `path:"org-slug-or-id"`
}

// CreateProjectParams is the request parameters for createProject.
type CreateProjectParams struct {
	OrgSlugOrID string             `path:"org-slug-or-id"`
	Body        *CreateProjectBody `body:"application/json"`
}

// ListURLOrbAllowListEntriesParams is the request parameters for listURLOrbAllowListEntries.
type ListURLOrbAllowListEntriesParams struct {
	OrgSlugOrID string `path:"org-slug-or-id"`
}

// CreateURLOrbAllowListEntryParams is the request parameters for createURLOrbAllowListEntry.
type CreateURLOrbAllowListEntryParams struct {
	OrgSlugOrID string                          `path:"org-slug-or-id"`
	Body        *CreateURLOrbAllowListEntryBody `body:"application/json"`
}

// RemoveURLOrbAllowListEntryParams is the request parameters for removeURLOrbAllowListEntry.
type RemoveURLOrbAllowListEntryParams struct {
	OrgSlugOrID      string `path:"org-slug-or-id"`
	AllowListEntryID string `path:"allow-list-entry-id"`
}

// ListPipelinesParams is the request parameters for listPipelines.
type ListPipelinesParams struct {
	OrgSlug   *string `query:"org-slug"`
	PageToken *string `query:"page-token"`
	Mine      *bool   `query:"mine"`
}

// ContinuePipelineParams is the request parameters for continuePipeline.
type ContinuePipelineParams struct {
	Body *ContinuePipelineBody `body:"application/json"`
}

// GetPipelineByIDParams is the request parameters for getPipelineById.
type GetPipelineByIDParams struct {
	PipelineID string `path:"pipeline-id"`
}

// GetPipelineConfigByIDParams is the request parameters for getPipelineConfigById.
type GetPipelineConfigByIDParams struct {
	PipelineID string `path:"pipeline-id"`
}

// GetPipelineValuesByIDParams is the request parameters for getPipelineValuesById.
type GetPipelineValuesByIDParams struct {
	PipelineID string `path:"pipeline-id"`
}

// ListWorkflowsByPipelineIDParams is the request parameters for listWorkflowsByPipelineId.
type ListWorkflowsByPipelineIDParams struct {
	PipelineID string  `path:"pipeline-id"`
	PageToken  *string `query:"page-token"`
}

// GetProjectBySlugParams is the request parameters for getProjectBySlug.
type GetProjectBySlugParams struct {
	Provider     string `path:"provider"`
	Organization string `path:"organization"`
	Project      string `path:"project"`
}

// CreateProject1Params is the request parameters for createProject1.
type CreateProject1Params struct {
	Provider string `path:"provider"`
}

// DeleteProjectBySlugParams is the request parameters for deleteProjectBySlug.
type DeleteProjectBySlugParams struct {
	Provider     string `path:"provider"`
	Organization string `path:"organization"`
	Project      string `path:"project"`
}

// ListCheckoutKeysParams is the request parameters for listCheckoutKeys.
type ListCheckoutKeysParams struct {
	Provider     string  `path:"provider"`
	Organization string  `path:"organization"`
	Project      string  `path:"project"`
	Digest       *string `query:"digest"`
}

// CreateCheckoutKeyParams is the request parameters for createCheckoutKey.
type CreateCheckoutKeyParams struct {
	Provider     string                 `path:"provider"`
	Organization string                 `path:"organization"`
	Project      string                 `path:"project"`
	Body         *CreateCheckoutKeyBody `body:"application/json"`
}

// GetCheckoutKeyParams is the request parameters for getCheckoutKey.
type GetCheckoutKeyParams struct {
	Provider     string `path:"provider"`
	Organization string `path:"organization"`
	Project      string `path:"project"`
	Fingerprint  string `path:"fingerprint"`
}

// DeleteCheckoutKeyParams is the request parameters for deleteCheckoutKey.
type DeleteCheckoutKeyParams struct {
	Provider     string `path:"provider"`
	Organization string `path:"organization"`
	Project      string `path:"project"`
	Fingerprint  string `path:"fingerprint"`
}

// ListEnvVarsParams is the request parameters for listEnvVars.
type ListEnvVarsParams struct {
	Provider     string `path:"provider"`
	Organization string `path:"organization"`
	Project      string `path:"project"`
}

// CreateEnvVarParams is the request parameters for createEnvVar.
type CreateEnvVarParams struct {
	Provider     string            `path:"provider"`
	Organization string            `path:"organization"`
	Project      string            `path:"project"`
	Body         *CreateEnvVarBody `body:"application/json"`
}

// GetEnvVarParams is the request parameters for getEnvVar.
type GetEnvVarParams struct {
	Provider     string `path:"provider"`
	Organization string `path:"organization"`
	Project      string `path:"project"`
	Name         string `path:"name"`
}

// DeleteEnvVarOpParams is the request parameters for deleteEnvVar.
type DeleteEnvVarOpParams struct {
	Provider     string `path:"provider"`
	Organization string `path:"organization"`
	Project      string `path:"project"`
	Name         string `path:"name"`
}

// GetJobDetailsParams is the request parameters for getJobDetails.
type GetJobDetailsParams struct {
	JobNumber    any    `path:"job-number"`
	Provider     string `path:"provider"`
	Organization string `path:"organization"`
	Project      string `path:"project"`
}

// CancelJobByJobNumberParams is the request parameters for cancelJobByJobNumber.
type CancelJobByJobNumberParams struct {
	JobNumber    any    `path:"job-number"`
	Provider     string `path:"provider"`
	Organization string `path:"organization"`
	Project      string `path:"project"`
}

// ListPipelinesForProjectParams is the request parameters for listPipelinesForProject.
type ListPipelinesForProjectParams struct {
	Provider     string  `path:"provider"`
	Organization string  `path:"organization"`
	Project      string  `path:"project"`
	Branch       *string `query:"branch"`
	PageToken    *string `query:"page-token"`
}

// TriggerPipelineParams is the request parameters for triggerPipeline.
type TriggerPipelineParams struct {
	Provider     string               `path:"provider"`
	Organization string               `path:"organization"`
	Project      string               `path:"project"`
	Body         *TriggerPipelineBody `body:"application/json"`
}

// ListMyPipelinesParams is the request parameters for listMyPipelines.
type ListMyPipelinesParams struct {
	Provider     string  `path:"provider"`
	Organization string  `path:"organization"`
	Project      string  `path:"project"`
	PageToken    *string `query:"page-token"`
}

// GetPipelineByNumberParams is the request parameters for getPipelineByNumber.
type GetPipelineByNumberParams struct {
	Provider       string `path:"provider"`
	Organization   string `path:"organization"`
	Project        string `path:"project"`
	PipelineNumber any    `path:"pipeline-number"`
}

// ListSchedulesForProjectParams is the request parameters for listSchedulesForProject.
type ListSchedulesForProjectParams struct {
	Provider     string  `path:"provider"`
	Organization string  `path:"organization"`
	Project      string  `path:"project"`
	PageToken    *string `query:"page-token"`
}

// CreateScheduleParams is the request parameters for createSchedule.
type CreateScheduleParams struct {
	Provider     string              `path:"provider"`
	Organization string              `path:"organization"`
	Project      string              `path:"project"`
	Body         *CreateScheduleBody `body:"application/json"`
}

// GetJobArtifactsParams is the request parameters for getJobArtifacts.
type GetJobArtifactsParams struct {
	JobNumber    any    `path:"job-number"`
	Provider     string `path:"provider"`
	Organization string `path:"organization"`
	Project      string `path:"project"`
}

// GetTestsParams is the request parameters for getTests.
type GetTestsParams struct {
	JobNumber    any    `path:"job-number"`
	Provider     string `path:"provider"`
	Organization string `path:"organization"`
	Project      string `path:"project"`
}

// GetScheduleByIDParams is the request parameters for getScheduleById.
type GetScheduleByIDParams struct {
	ScheduleID string `path:"schedule-id"`
}

// UpdateScheduleParams is the request parameters for updateSchedule.
type UpdateScheduleParams struct {
	ScheduleID string              `path:"schedule-id"`
	Body       *UpdateScheduleBody `body:"application/json"`
}

// DeleteScheduleByIDParams is the request parameters for deleteScheduleById.
type DeleteScheduleByIDParams struct {
	ScheduleID string `path:"schedule-id"`
}

// GetUserParams is the request parameters for getUser.
type GetUserParams struct {
	ID string `path:"id"`
}

// GetWebhooksParams is the request parameters for getWebhooks.
type GetWebhooksParams struct {
	ScopeID   string `query:"scope-id"`
	ScopeType string `query:"scope-type"`
}

// CreateWebhookParams is the request parameters for createWebhook.
type CreateWebhookParams struct {
	Body *CreateWebhookBody `body:"application/json"`
}

// GetWebhookByIDParams is the request parameters for getWebhookById.
type GetWebhookByIDParams struct {
	WebhookID string `path:"webhook-id"`
}

// UpdateWebhookParams is the request parameters for updateWebhook.
type UpdateWebhookParams struct {
	WebhookID string             `path:"webhook-id"`
	Body      *UpdateWebhookBody `body:"application/json"`
}

// DeleteWebhookParams is the request parameters for deleteWebhook.
type DeleteWebhookParams struct {
	WebhookID string `path:"webhook-id"`
}

// GetWorkflowByIDParams is the request parameters for getWorkflowById.
type GetWorkflowByIDParams struct {
	ID string `path:"id"`
}

// ApprovePendingApprovalJobByIDParams is the request parameters for approvePendingApprovalJobById.
type ApprovePendingApprovalJobByIDParams struct {
	ApprovalRequestID string `path:"approval_request_id"`
	ID                string `path:"id"`
}

// CancelWorkflowParams is the request parameters for cancelWorkflow.
type CancelWorkflowParams struct {
	ID string `path:"id"`
}

// ListWorkflowJobsParams is the request parameters for listWorkflowJobs.
type ListWorkflowJobsParams struct {
	ID        string  `path:"id"`
	PageToken *string `query:"page-token"`
}

// RerunWorkflowParams is the request parameters for rerunWorkflow.
type RerunWorkflowParams struct {
	ID   string             `path:"id"`
	Body *RerunWorkflowBody `body:"application/json"`
}

// GetOrgClaimsParams is the request parameters for GetOrgClaims.
type GetOrgClaimsParams struct {
	OrgID string `path:"orgID"`
}

// PatchOrgClaimsParams is the request parameters for PatchOrgClaims.
type PatchOrgClaimsParams struct {
	OrgID string              `path:"orgID"`
	Body  *PatchClaimsRequest `body:"application/json"`
}

// DeleteOrgClaimsParams is the request parameters for DeleteOrgClaims.
type DeleteOrgClaimsParams struct {
	OrgID  string `path:"orgID"`
	Claims string `query:"claims"`
}

// GetProjectClaimsParams is the request parameters for GetProjectClaims.
type GetProjectClaimsParams struct {
	OrgID     string `path:"orgID"`
	ProjectID string `path:"projectID"`
}

// PatchProjectClaimsParams is the request parameters for PatchProjectClaims.
type PatchProjectClaimsParams struct {
	OrgID     string              `path:"orgID"`
	ProjectID string              `path:"projectID"`
	Body      *PatchClaimsRequest `body:"application/json"`
}

// DeleteProjectClaimsParams is the request parameters for DeleteProjectClaims.
type DeleteProjectClaimsParams struct {
	OrgID     string `path:"orgID"`
	ProjectID string `path:"projectID"`
	Claims    string `query:"claims"`
}

// GetDecisionLogsParams is the request parameters for GetDecisionLogs.
type GetDecisionLogsParams struct {
	OwnerID     string     `path:"ownerID"`
	Context     string     `path:"context"`
	Status      *string    `query:"status"`
	After       *time.Time `query:"after"`
	Before      *time.Time `query:"before"`
	Branch      *string    `query:"branch"`
	ProjectID   *string    `query:"project_id"`
	BuildNumber *string    `query:"build_number"`
	Offset      *int64     `query:"offset"`
}

// MakeDecisionParams is the request parameters for MakeDecision.
type MakeDecisionParams struct {
	OwnerID string            `path:"ownerID"`
	Context string            `path:"context"`
	Body    *MakeDecisionBody `body:"application/json"`
}

// GetDecisionSettingsParams is the request parameters for GetDecisionSettings.
type GetDecisionSettingsParams struct {
	OwnerID string `path:"ownerID"`
	Context string `path:"context"`
}

// SetDecisionSettingsParams is the request parameters for SetDecisionSettings.
type SetDecisionSettingsParams struct {
	OwnerID string            `path:"ownerID"`
	Context string            `path:"context"`
	Body    *DecisionSettings `body:"application/json"`
}

// GetDecisionLogParams is the request parameters for GetDecisionLog.
type GetDecisionLogParams struct {
	OwnerID    string `path:"ownerID"`
	Context    string `path:"context"`
	DecisionID string `path:"decisionID"`
}

// GetDecisionLogPolicyBundleParams is the request parameters for GetDecisionLogPolicyBundle.
type GetDecisionLogPolicyBundleParams struct {
	OwnerID    string `path:"ownerID"`
	Context    string `path:"context"`
	DecisionID string `path:"decisionID"`
}

// GetPolicyBundleParams is the request parameters for GetPolicyBundle.
type GetPolicyBundleParams struct {
	OwnerID string `path:"ownerID"`
	Context string `path:"context"`
}

// CreatePolicyBundleParams is the request parameters for CreatePolicyBundle.
type CreatePolicyBundleParams struct {
	OwnerID string         `path:"ownerID"`
	Context string         `path:"context"`
	Dry     *bool          `query:"dry"`
	Body    *BundlePayload `body:"application/json"`
}

// GetPolicyDocumentParams is the request parameters for GetPolicyDocument.
type GetPolicyDocumentParams struct {
	OwnerID    string `path:"ownerID"`
	Context    string `path:"context"`
	PolicyName string `path:"policyName"`
}

// ListContextsParams is the request parameters for listContexts.
type ListContextsParams struct {
	OwnerID   *string `query:"owner-id"`
	OwnerSlug *string `query:"owner-slug"`
	OwnerType *string `query:"owner-type"`
	PageToken *string `query:"page-token"`
}

// CreateContextParams is the request parameters for createContext.
type CreateContextParams struct {
	Body *ContextCreated `body:"application/json"`
}

// GetContextParams is the request parameters for getContext.
type GetContextParams struct {
	ContextID string `path:"context_id"`
}

// DeleteContextParams is the request parameters for deleteContext.
type DeleteContextParams struct {
	ContextID string `path:"context_id"`
}

// ListEnvironmentVariablesFromContextParams is the request parameters for listEnvironmentVariablesFromContext.
type ListEnvironmentVariablesFromContextParams struct {
	ContextID string  `path:"context_id"`
	PageToken *string `query:"page-token"`
}

// AddEnvironmentVariableToContextParams is the request parameters for addEnvironmentVariableToContext.
type AddEnvironmentVariableToContextParams struct {
	ContextID  string                               `path:"context_id"`
	EnvVarName string                               `path:"env_var_name"`
	Body       *AddEnvironmentVariableToContextBody `body:"application/json"`
}

// DeleteEnvironmentVariableFromContextParams is the request parameters for deleteEnvironmentVariableFromContext.
type DeleteEnvironmentVariableFromContextParams struct {
	ContextID  string `path:"context_id"`
	EnvVarName string `path:"env_var_name"`
}

// GetContextRestrictionsParams is the request parameters for getContextRestrictions.
type GetContextRestrictionsParams struct {
	ContextID string `path:"context_id"`
}

// CreateContextRestrictionParams is the request parameters for createContextRestriction.
type CreateContextRestrictionParams struct {
	ContextID string                       `path:"context_id"`
	Body      CreateContextRestrictionBody `body:"application/json"`
}

// DeleteContextRestrictionParams is the request parameters for deleteContextRestriction.
type DeleteContextRestrictionParams struct {
	ContextID     string `path:"context_id"`
	RestrictionID string `path:"restriction_id"`
}

// GetProjectSettingsParams is the request parameters for getProjectSettings.
type GetProjectSettingsParams struct {
	Provider     string `path:"provider"`
	Organization string `path:"organization"`
	Project      string `path:"project"`
}

// PatchProjectSettingsParams is the request parameters for patchProjectSettings.
type PatchProjectSettingsParams struct {
	Provider     string          `path:"provider"`
	Organization string          `path:"organization"`
	Project      string          `path:"project"`
	Body         ProjectSettings `body:"application/json"`
}

// GetOrganizationGroupsParams is the request parameters for getOrganizationGroups.
type GetOrganizationGroupsParams struct {
	OrgID     string  `path:"org_id"`
	Limit     *int64  `query:"limit"`
	PageToken *string `query:"page-token"`
}

// CreateOrganizationGroupParams is the request parameters for createOrganizationGroup.
type CreateOrganizationGroupParams struct {
	OrgID string                      `path:"org_id"`
	Body  CreateOrganizationGroupBody `body:"application/json"`
}

// GetGroupParams is the request parameters for getGroup.
type GetGroupParams struct {
	OrgID   string `path:"org_id"`
	GroupID string `path:"group_id"`
}

// DeleteGroupParams is the request parameters for deleteGroup.
type DeleteGroupParams struct {
	OrgID   string `path:"org_id"`
	GroupID string `path:"group_id"`
}

// CreateUsageExportParams is the request parameters for createUsageExport.
type CreateUsageExportParams struct {
	OrgID string                `path:"org_id"`
	Body  CreateUsageExportBody `body:"application/json"`
}

// GetUsageExportParams is the request parameters for getUsageExport.
type GetUsageExportParams struct {
	OrgID            string `path:"org_id"`
	UsageExportJobID string `path:"usage_export_job_id"`
}

// TriggerPipelineRunParams is the request parameters for triggerPipelineRun.
type TriggerPipelineRunParams struct {
	Provider     string                  `path:"provider"`
	Organization string                  `path:"organization"`
	Project      string                  `path:"project"`
	Body         *TriggerPipelineRequest `body:"application/json"`
}

// ListPipelineDefinitionsParams is the request parameters for listPipelineDefinitions.
type ListPipelineDefinitionsParams struct {
	ProjectID string `path:"project_id"`
}

// CreatePipelineDefinitionParams is the request parameters for createPipelineDefinition.
type CreatePipelineDefinitionParams struct {
	ProjectID string                           `path:"project_id"`
	Body      *CreatePipelineDefinitionRequest `body:"application/json"`
}

// GetPipelineDefinitionParams is the request parameters for getPipelineDefinition.
type GetPipelineDefinitionParams struct {
	ProjectID            string `path:"project_id"`
	PipelineDefinitionID string `path:"pipeline_definition_id"`
}

// UpdatePipelineDefinitionParams is the request parameters for updatePipelineDefinition.
type UpdatePipelineDefinitionParams struct {
	ProjectID            string                           `path:"project_id"`
	PipelineDefinitionID string                           `path:"pipeline_definition_id"`
	Body                 *UpdatePipelineDefinitionRequest `body:"application/json"`
}

// DeletePipelineDefinitionParams is the request parameters for deletePipelineDefinition.
type DeletePipelineDefinitionParams struct {
	ProjectID            string `path:"project_id"`
	PipelineDefinitionID string `path:"pipeline_definition_id"`
}

// ListPipelineDefinitionTriggersParams is the request parameters for listPipelineDefinitionTriggers.
type ListPipelineDefinitionTriggersParams struct {
	ProjectID            string `path:"project_id"`
	PipelineDefinitionID string `path:"pipeline_definition_id"`
}

// CreateTriggerParams is the request parameters for createTrigger.
type CreateTriggerParams struct {
	ProjectID            string                `path:"project_id"`
	PipelineDefinitionID string                `path:"pipeline_definition_id"`
	Body                 *CreateTriggerRequest `body:"application/json"`
}

// GetTriggerParams is the request parameters for getTrigger.
type GetTriggerParams struct {
	ProjectID string `path:"project_id"`
	TriggerID string `path:"trigger_id"`
}

// UpdateTriggerParams is the request parameters for updateTrigger.
type UpdateTriggerParams struct {
	ProjectID string                `path:"project_id"`
	TriggerID string                `path:"trigger_id"`
	Body      *UpdateTriggerRequest `body:"application/json"`
}

// DeleteTriggerParams is the request parameters for deleteTrigger.
type DeleteTriggerParams struct {
	ProjectID string `path:"project_id"`
	TriggerID string `path:"trigger_id"`
}

// RollbackProjectParams is the request parameters for rollbackProject.
type RollbackProjectParams struct {
	ProjectID string                 `path:"project_id"`
	Body      RollbackProjectRequest `body:"application/json"`
}

// ListEnvironmentsParams is the request parameters for listEnvironments.
type ListEnvironmentsParams struct {
	OrgID     string  `query:"org-id"`
	PageSize  int64   `query:"page-size"`
	PageToken *string `query:"page-token"`
}

// GetEnvironmentParams is the request parameters for getEnvironment.
type GetEnvironmentParams struct {
	EnvironmentID string `path:"environment_id"`
}

// ListComponentsParams is the request parameters for listComponents.
type ListComponentsParams struct {
	OrgID     string  `query:"org-id"`
	ProjectID *string `query:"project-id"`
	PageSize  int64   `query:"page-size"`
	PageToken *string `query:"page-token"`
}

// GetComponentParams is the request parameters for getComponent.
type GetComponentParams struct {
	ComponentID string `path:"component_id"`
}

// ListComponentVersionsParams is the request parameters for listComponentVersions.
type ListComponentVersionsParams struct {
	ComponentID   string  `path:"component_id"`
	EnvironmentID *string `query:"environment-id"`
}
